package live.tikgik.expenses.shared.error.exception;

public enum ErrorCode {
	MISSING_USERNAME("API_001"),
	MISSING_PASSWORD("API_002"),
	MISSING_USER_ID("API_003"),
	UNABLE_TO_HASH_PASSWORD("API_004"),
	INVALID_USERNAME_OR_PASSWORD("API_005"),
	USER_IS_NOT_FOUND("API_006"),
	CST_IS_NOT_FOUND("API_007"),
	INVALID_Date("API_008"),
	YOU_EXCEED_NUMBER_OF_RETRIALS("API_009"),
	CUSTOMER_IS_BLOCKED("API_010"),
	INVALID_OTP_IS_USED_BEFORE("API_011"),
	INVALID_PIN_AUTHENTICATION("API_012"),
	INVALID_OTP_AUTHENTICATION("API_013"),
	INVALID_PASSWORD_AUTHENTICATION("API_014"),
	INVALID_OTP_IS_NOT_FOUND("API_015"),
	DELETED_USER("API_016"),

	INVALID_ACCOUNTNUMBER("API_017"),
	INVALID_MOBILE_NUMBER ("API_018"),
	OBJECT_NOT_FOUND("DB_001"),
	INVALID_VERIFICATION_TOKEN("API_019"),
	AMOUNT_NOT_EQUAL("DB_002");

	private String value;
	
	private ErrorCode(String value)
	{
		this.value = value;
	}
	
	public String getErrorCode()
	{
		return value;
	}
}
